services:
  postgres:
    image: postgres:16.6-alpine
    profiles:
      - infra
    container_name: ${DB_CONTAINER_NAME}
    environment:
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_DATABASE}
    expose:
      - "${DB_PORT}"
    volumes:
      - ${DB_VOLUME_NAME}/data:/var/lib/postgresql/data
    networks:
      - todolist
    restart: always

  backend:
    depends_on:
      - postgres
    image: ${SERVICE_BACKEND_CONTAINER_NAME}
    build: ./packages/server
    profiles:
      - infra
    container_name: ${SERVICE_BACKEND_CONTAINER_NAME}
    expose:
      - "${SERVER_PORT}"
    ports:
      - "${SERVER_PORT}:${SERVER_PORT}"
    networks:
      - todolist
    restart: always

  client:
    image: ${SERVICE_FRONTEND_CONTAINER_NAME}
    build: ./packages/client
    profiles:
      - services
    container_name: ${SERVICE_FRONTEND_CONTAINER_NAME}
    ports:
      - "${CLIENT_PORT}:${CLIENT_PORT}"
    networks:
      - todolist
    restart: always

  stories:
    image: ${SERVICE_STORYBOOK_CONTAINER_NAME}
    build: ./packages/stories
    profiles:
      - development
    container_name: ${SERVICE_STORYBOOK_CONTAINER_NAME}
    ports:
      - "${STORIES_PORT}:${STORIES_PORT}"
    networks:
      - todolist
    restart: always

networks:
  todolist:
    external: true
